# Generated by Django 5.2.6 on 2025-09-15 18:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código de Rastreamento')),
                ('status', models.CharField(choices=[('assigned', 'Atribuída'), ('picked_up', 'Coletada'), ('in_transit', 'Em Trânsito'), ('delivered', 'Entregue'), ('failed', 'Falha na Entrega'), ('returned', 'Devolvida')], default='assigned', max_length=20, verbose_name='Status')),
                ('estimated_delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Data Estimada de Entrega')),
                ('actual_delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Data Real de Entrega')),
                ('delivery_address', models.TextField(verbose_name='Endereço de Entrega')),
                ('delivery_city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('delivery_state', models.CharField(max_length=100, verbose_name='Estado')),
                ('delivery_postal_code', models.CharField(max_length=10, verbose_name='CEP')),
                ('delivery_country', models.CharField(default='Brasil', max_length=100, verbose_name='País')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('customer_phone', models.CharField(max_length=17, verbose_name='Telefone do Cliente')),
                ('delivery_instructions', models.TextField(blank=True, verbose_name='Instruções de Entrega')),
                ('delivery_notes', models.TextField(blank=True, verbose_name='Observações da Entrega')),
                ('recipient_name', models.CharField(blank=True, max_length=255, verbose_name='Nome do Recebedor')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='delivery_signatures/', verbose_name='Imagem da Assinatura')),
                ('delivery_photo', models.ImageField(blank=True, null=True, upload_to='delivery_photos/', verbose_name='Foto da Entrega')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Atribuído em')),
                ('picked_up_at', models.DateTimeField(blank=True, null=True, verbose_name='Coletado em')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregue em')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Avaliação')),
                ('comment', models.TextField(blank=True, verbose_name='Comentário')),
                ('delivery_time_rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Avaliação do Tempo de Entrega')),
                ('driver_rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Avaliação do Motorista')),
                ('package_condition_rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Avaliação da Condição do Pacote')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Feedback da Entrega',
                'verbose_name_plural': 'Feedbacks das Entregas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Início')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Término')),
                ('total_deliveries', models.PositiveIntegerField(default=0, verbose_name='Total de Entregas')),
                ('completed_deliveries', models.PositiveIntegerField(default=0, verbose_name='Entregas Concluídas')),
                ('failed_deliveries', models.PositiveIntegerField(default=0, verbose_name='Entregas Falhadas')),
                ('total_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Distância Total (km)')),
                ('fuel_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Custo de Combustível')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Rota Concluída')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Rota de Entrega',
                'verbose_name_plural': 'Rotas de Entrega',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Atribuída'), ('picked_up', 'Coletada'), ('in_transit', 'Em Trânsito'), ('delivered', 'Entregue'), ('failed', 'Falha na Entrega'), ('returned', 'Devolvida')], max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Localização')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Histórico de Status da Entrega',
                'verbose_name_plural': 'Históricos de Status das Entregas',
                'ordering': ['-created_at'],
            },
        ),
    ]
